### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Axkaban** [pedrohenriquedias/bomberman#1]
Thanks for the [comments](https://github.com/pedrohenriquedias/bomberman/blob/master/codecademy-capstone-project/index.html#L13)

Good use of the [`alt` attribute](https://github.com/pedrohenriquedias/bomberman/blob/master/codecademy-capstone-project/cart.html#L16)

Nice use of [input attributes](https://github.com/pedrohenriquedias/bomberman/blob/master/codecademy-capstone-project/cart.html#L83)

Great use of[ ids and classes ](https://github.com/pedrohenriquedias/bomberman/blob/master/codecademy-capstone-project/living.html#L33-L34)

Remember to have child elements on a new line.
```
<div id="main" class="product-list-section">
      <ul class="breadcrumb">
        <li>
            <a href="products.html">All Products</a> //here
        </li>
        <li>Living Room</li>
      </ul>
```
You can see the same in other sections that involve [anchor tags](https://github.com/pedrohenriquedias/bomberman/blob/master/codecademy-capstone-project/deals.html#L21)

```
  <a href="cart.html" class="button cart" role="button">  
      Cart 
      <img src="resources/img/cart.svg" alt="Mini cart">
  </a>
```
Creating those spaces make it more legible and easier to debug if needed.

**Comment by phdro88** [comment]
Hi, Axkaban! Thanks for the tips! Next time I'll pay more attention to the spaces and the position of child elements on the code. Thank you!
