### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Axkaban** [pedrohenriquedias/bomberman#2]
Again, thank you for the [comments](https://github.com/pedrohenriquedias/bomberman/blob/master/codecademy-capstone-project/resources/css/base.css#L128) 

Love your base.css code! 

Great implementations of grid, now just make sure you also keep in mind browsers that might not directly read `grid` as a `display` value will need to be preceded by another `display` with the value `-ms-grid` for example, in case of Internet Explorer.
```
display: -ms-grid; 
  display: grid;
```

[here](https://stackoverflow.com/questions/45124230/css-display-grid-and-or-ms-grid#45124295)'s a question on stackoverflow related to ordering those properties.

Also great work on your [grid-template-areas](https://github.com/pedrohenriquedias/bomberman/blob/master/codecademy-capstone-project/resources/css/sell.css#L78-L82)

**Comment by phdro88** [comment]
Hi,  Axkaban! I didn't know that we needed to include the `-ms-grid` value for Internet Explorer. Thanks for the advice!

I'm very glad that you liked my code! Thank you!
