### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [pedrohenriquedias/bomberman#3]
Grade: **Met requirements, passed expectations**

That was some great work! Your use of syntax and new lines, as well as new line selectors in case of css grouped selectors, were well implemented. I was very happy with your transitions and media queries.

If you are interested in exploring mobile firs development for your styling, you can check [this article](https://www.uxpin.com/studio/blog/a-hands-on-guide-to-mobile-first-design/).

Best of luck!

**Comment by phdro88** [comment]
Thanks for the review, Axkaban! It was a great journey! I'll keep studying to get even better!

I'm surely interested in *mobile first development*, thanks for tip. I'll read the article as soon as possible.

Again, thank you for the help!
